version: '3.1'

services:
  phoenix:
    build:
      context: .
    environment:
      SECRET_KEY_BASE: SrfhEwb782iQDMjmpSNK0jeCUmxDBXf3zKxCHkEZ5pqDiVu50X0Dqa48tliuUXgx
      # Variables to connect to the Postgres server
      PG_USER: justin
      PG_PASS: mypassword
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: beespot
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: justin
      POSTGRES_DB: beespot
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
